### ISSUE TITLE
Full Screen exoplayer

### ISSUE THREAD

**Issue by chat2goku** [rubenquadros/Jetpack-Compose-Video-Games-Example#10]
Is full screen exoplayer coming?

**Comment by rubenquadros** [comment]
Not yet, I haven't done much work on this project recently. Let me know if it's something of interest then I'll look into it over the weekend.

**Comment by rubenquadros** [comment]
Full screen exoplayer is available now
https://github.com/rubenquadros/Jetpack-Compose-Video-Games-Example/pull/11
